/* AUTO-GENERATED by tools/gen.tcl from libdatachannel rtc.h.
 * Do not edit. Regenerate after libdatachannel header changes.
 */
#include "rtc_runtime.h"
#include "rtc_generated.h"
#include <rtc/rtc.h>
#include <tcl.h>
#include <string.h>

const char *RtcEnumStr_rtc_nal_unit_separator(int v) {
    switch (v) {
        case 0: return "nal-separator-length";
        case 1: return "nal-separator-long-start-sequence";
        case 2: return "nal-separator-short-start-sequence";
        case 3: return "nal-separator-start-sequence";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_obu_packetization(int v) {
    switch (v) {
        case 0: return "obu-packetized-obu";
        case 1: return "obu-packetized-temporal-unit";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_transport_policy(int v) {
    switch (v) {
        case 0: return "transport-policy-all";
        case 1: return "transport-policy-relay";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_direction(int v) {
    switch (v) {
        case 0: return "direction-unknown";
        case 1: return "direction-sendonly";
        case 2: return "direction-recvonly";
        case 3: return "direction-sendrecv";
        case 4: return "direction-inactive";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_certificate_type(int v) {
    switch (v) {
        case 0: return "certificate-default";
        case 1: return "certificate-ecdsa";
        case 2: return "certificate-rsa";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_signaling_state(int v) {
    switch (v) {
        case 0: return "signaling-stable";
        case 1: return "signaling-have-local-offer";
        case 2: return "signaling-have-remote-offer";
        case 3: return "signaling-have-local-pranswer";
        case 4: return "signaling-have-remote-pranswer";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_state(int v) {
    switch (v) {
        case 0: return "new";
        case 1: return "connecting";
        case 2: return "connected";
        case 3: return "disconnected";
        case 4: return "failed";
        case 5: return "closed";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_codec(int v) {
    switch (v) {
        case 0: return "codec-h264";
        case 1: return "codec-vp8";
        case 2: return "codec-vp9";
        case 3: return "codec-h265";
        case 4: return "codec-av1";
        case 128: return "codec-opus";
        case 129: return "codec-pcmu";
        case 130: return "codec-pcma";
        case 131: return "codec-aac";
        case 132: return "codec-g722";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_log_level(int v) {
    switch (v) {
        case 0: return "log-none";
        case 1: return "log-fatal";
        case 2: return "log-error";
        case 3: return "log-warning";
        case 4: return "log-info";
        case 5: return "log-debug";
        case 6: return "log-verbose";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_gathering_state(int v) {
    switch (v) {
        case 0: return "gathering-new";
        case 1: return "gathering-inprogress";
        case 2: return "gathering-complete";
        default: return "unknown";
    }
}

const char *RtcEnumStr_rtc_ice_state(int v) {
    switch (v) {
        case 0: return "ice-new";
        case 1: return "ice-checking";
        case 2: return "ice-connected";
        case 3: return "ice-completed";
        case 4: return "ice-failed";
        case 5: return "ice-disconnected";
        case 6: return "ice-closed";
        default: return "unknown";
    }
}

static int Cmd_pc_close(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    int rc = rtcClosePeerConnection(raw_pc);
    return RtcReturnInt(interp, rc);
}

static int Cmd_pc_delete(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    int rc = rtcDeletePeerConnection(raw_pc);
    RtcUnregisterAllCallbacks(raw_pc);
    return RtcReturnInt(interp, rc);
}

static void Tramp_pc_local_description(int pc, const char* sdp, const char* type, void* ptr) {
    (void)ptr;
    RtcEnqueueTwoStr(pc, RTC_SLOT_PC_LOCAL_DESCRIPTION, sdp, type);
}

static int Cmd_pc_on_local_description(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_PC_LOCAL_DESCRIPTION, objv[2],
        (RtcSetterFn)rtcSetLocalDescriptionCallback, (void(*)(void))Tramp_pc_local_description);
}

static void Tramp_pc_local_candidate(int pc, const char* cand, const char* mid, void* ptr) {
    (void)ptr;
    RtcEnqueueTwoStr(pc, RTC_SLOT_PC_LOCAL_CANDIDATE, cand, mid);
}

static int Cmd_pc_on_local_candidate(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_PC_LOCAL_CANDIDATE, objv[2],
        (RtcSetterFn)rtcSetLocalCandidateCallback, (void(*)(void))Tramp_pc_local_candidate);
}

static void Tramp_pc_state_change(int pc, rtcState state, void* ptr) {
    (void)ptr;
    RtcEnqueueString(pc, RTC_SLOT_PC_STATE_CHANGE, RtcEnumStr_rtc_state(state));
}

static int Cmd_pc_on_state_change(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_PC_STATE_CHANGE, objv[2],
        (RtcSetterFn)rtcSetStateChangeCallback, (void(*)(void))Tramp_pc_state_change);
}

static void Tramp_pc_ice_state_change(int pc, rtcIceState state, void* ptr) {
    (void)ptr;
    RtcEnqueueString(pc, RTC_SLOT_PC_ICE_STATE_CHANGE, RtcEnumStr_rtc_ice_state(state));
}

static int Cmd_pc_on_ice_state_change(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_PC_ICE_STATE_CHANGE, objv[2],
        (RtcSetterFn)rtcSetIceStateChangeCallback, (void(*)(void))Tramp_pc_ice_state_change);
}

static void Tramp_pc_gathering_state_change(int pc, rtcGatheringState state, void* ptr) {
    (void)ptr;
    RtcEnqueueString(pc, RTC_SLOT_PC_GATHERING_STATE_CHANGE, RtcEnumStr_rtc_gathering_state(state));
}

static int Cmd_pc_on_gathering_state_change(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_PC_GATHERING_STATE_CHANGE, objv[2],
        (RtcSetterFn)rtcSetGatheringStateChangeCallback, (void(*)(void))Tramp_pc_gathering_state_change);
}

static void Tramp_pc_signaling_state_change(int pc, rtcSignalingState state, void* ptr) {
    (void)ptr;
    RtcEnqueueString(pc, RTC_SLOT_PC_SIGNALING_STATE_CHANGE, RtcEnumStr_rtc_signaling_state(state));
}

static int Cmd_pc_on_signaling_state_change(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_PC_SIGNALING_STATE_CHANGE, objv[2],
        (RtcSetterFn)rtcSetSignalingStateChangeCallback, (void(*)(void))Tramp_pc_signaling_state_change);
}

static int Cmd_pc_set_local_description(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc type"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    const char *v_type = Tcl_GetString(objv[2]);
    int rc = rtcSetLocalDescription(raw_pc, v_type);
    return RtcReturnInt(interp, rc);
}

static int Cmd_pc_set_remote_description(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 4) { Tcl_WrongNumArgs(interp, 1, objv, "pc sdp type"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    const char *v_sdp = Tcl_GetString(objv[2]);
    const char *v_type = Tcl_GetString(objv[3]);
    int rc = rtcSetRemoteDescription(raw_pc, v_sdp, v_type);
    return RtcReturnInt(interp, rc);
}

static int Cmd_pc_add_remote_candidate(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 4) { Tcl_WrongNumArgs(interp, 1, objv, "pc cand mid"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    const char *v_cand = Tcl_GetString(objv[2]);
    const char *v_mid = Tcl_GetString(objv[3]);
    int rc = rtcAddRemoteCandidate(raw_pc, v_cand, v_mid);
    return RtcReturnInt(interp, rc);
}

static int Cmd_pc_get_local_description(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetLocalDescription, id);
}

static int Cmd_pc_get_remote_description(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetRemoteDescription, id);
}

static int Cmd_pc_get_local_description_type(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetLocalDescriptionType, id);
}

static int Cmd_pc_get_remote_description_type(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetRemoteDescriptionType, id);
}

static int Cmd_pc_create_offer(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcCreateOffer, id);
}

static int Cmd_pc_create_answer(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcCreateAnswer, id);
}

static int Cmd_pc_get_local_address(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetLocalAddress, id);
}

static int Cmd_pc_get_remote_address(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetRemoteAddress, id);
}

static int Cmd_pc_is_negotiation_needed(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    bool rc = rtcIsNegotiationNeeded(raw_pc);
    Tcl_SetObjResult(interp, Tcl_NewBooleanObj(rc));
    return TCL_OK;
}

static int Cmd_pc_get_max_data_channel_stream(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    int rc = rtcGetMaxDataChannelStream(raw_pc);
    return RtcReturnInt(interp, rc);
}

static int Cmd_pc_get_remote_max_message_size(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "pc"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    int rc = rtcGetRemoteMaxMessageSize(raw_pc);
    return RtcReturnInt(interp, rc);
}

static void Tramp_id_open(int id, void* ptr) {
    (void)ptr;
    RtcEnqueueNoArgs(id, RTC_SLOT_ID_OPEN);
}

static int Cmd_id_on_open(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "id cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_ID_OPEN, objv[2],
        (RtcSetterFn)rtcSetOpenCallback, (void(*)(void))Tramp_id_open);
}

static void Tramp_id_closed(int id, void* ptr) {
    (void)ptr;
    RtcEnqueueNoArgs(id, RTC_SLOT_ID_CLOSED);
}

static int Cmd_id_on_closed(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "id cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_ID_CLOSED, objv[2],
        (RtcSetterFn)rtcSetClosedCallback, (void(*)(void))Tramp_id_closed);
}

static void Tramp_id_error(int id, const char* error, void* ptr) {
    (void)ptr;
    RtcEnqueueString(id, RTC_SLOT_ID_ERROR, error);
}

static int Cmd_id_on_error(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "id cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_ID_ERROR, objv[2],
        (RtcSetterFn)rtcSetErrorCallback, (void(*)(void))Tramp_id_error);
}

static void Tramp_id_message(int id, const char* message, int size, void* ptr) {
    (void)ptr;
    RtcEnqueueBytes(id, RTC_SLOT_ID_MESSAGE, message, size);
}

static int Cmd_id_on_message(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "id cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_ID_MESSAGE, objv[2],
        (RtcSetterFn)rtcSetMessageCallback, (void(*)(void))Tramp_id_message);
}

static int Cmd_id_close(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "id"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    int rc = rtcClose(raw_id);
    return RtcReturnInt(interp, rc);
}

static int Cmd_id_delete(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "id"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    int rc = rtcDelete(raw_id);
    RtcUnregisterAllCallbacks(raw_id);
    return RtcReturnInt(interp, rc);
}

static int Cmd_id_is_open(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "id"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    bool rc = rtcIsOpen(raw_id);
    Tcl_SetObjResult(interp, Tcl_NewBooleanObj(rc));
    return TCL_OK;
}

static int Cmd_id_is_closed(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "id"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    bool rc = rtcIsClosed(raw_id);
    Tcl_SetObjResult(interp, Tcl_NewBooleanObj(rc));
    return TCL_OK;
}

static int Cmd_id_max_message_size(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "id"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    int rc = rtcMaxMessageSize(raw_id);
    return RtcReturnInt(interp, rc);
}

static int Cmd_id_get_buffered_amount(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "id"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    int rc = rtcGetBufferedAmount(raw_id);
    return RtcReturnInt(interp, rc);
}

static int Cmd_id_set_buffered_amount_low_threshold(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "id amount"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    int raw_amount;
    if (Tcl_GetIntFromObj(interp, objv[2], &raw_amount) != TCL_OK) return TCL_ERROR;
    int rc = rtcSetBufferedAmountLowThreshold(raw_id, raw_amount);
    return RtcReturnInt(interp, rc);
}

static void Tramp_id_buffered_amount_low(int id, void* ptr) {
    (void)ptr;
    RtcEnqueueNoArgs(id, RTC_SLOT_ID_BUFFERED_AMOUNT_LOW);
}

static int Cmd_id_on_buffered_amount_low(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "id cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_ID_BUFFERED_AMOUNT_LOW, objv[2],
        (RtcSetterFn)rtcSetBufferedAmountLowCallback, (void(*)(void))Tramp_id_buffered_amount_low);
}

static int Cmd_id_get_available_amount(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "id"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    int rc = rtcGetAvailableAmount(raw_id);
    return RtcReturnInt(interp, rc);
}

static void Tramp_id_available(int id, void* ptr) {
    (void)ptr;
    RtcEnqueueNoArgs(id, RTC_SLOT_ID_AVAILABLE);
}

static int Cmd_id_on_available(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "id cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_ID_AVAILABLE, objv[2],
        (RtcSetterFn)rtcSetAvailableCallback, (void(*)(void))Tramp_id_available);
}

static void Tramp_pc_data_channel(int pc, int dc, void* ptr) {
    (void)ptr;
    RtcEnqueueInt(pc, RTC_SLOT_PC_DATA_CHANNEL, dc);
}

static int Cmd_pc_on_data_channel(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_PC_DATA_CHANNEL, objv[2],
        (RtcSetterFn)rtcSetDataChannelCallback, (void(*)(void))Tramp_pc_data_channel);
}

static int Cmd_pc_create_data_channel(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc label"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    const char *v_label = Tcl_GetString(objv[2]);
    int rc = rtcCreateDataChannel(raw_pc, v_label);
    return RtcReturnInt(interp, rc);
}

static int Cmd_dc_delete(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "dc"); return TCL_ERROR; }
    int raw_dc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_dc) != TCL_OK) return TCL_ERROR;
    int rc = rtcDeleteDataChannel(raw_dc);
    RtcUnregisterAllCallbacks(raw_dc);
    return RtcReturnInt(interp, rc);
}

static int Cmd_dc_get_stream(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "dc"); return TCL_ERROR; }
    int raw_dc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_dc) != TCL_OK) return TCL_ERROR;
    int rc = rtcGetDataChannelStream(raw_dc);
    return RtcReturnInt(interp, rc);
}

static int Cmd_dc_get_label(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "dc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetDataChannelLabel, id);
}

static int Cmd_dc_get_protocol(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "dc"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetDataChannelProtocol, id);
}

static void Tramp_pc_track(int pc, int tr, void* ptr) {
    (void)ptr;
    RtcEnqueueInt(pc, RTC_SLOT_PC_TRACK, tr);
}

static int Cmd_pc_on_track(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_PC_TRACK, objv[2],
        (RtcSetterFn)rtcSetTrackCallback, (void(*)(void))Tramp_pc_track);
}

static int Cmd_pc_add_track(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "pc mediaDescriptionSdp"); return TCL_ERROR; }
    int raw_pc;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_pc) != TCL_OK) return TCL_ERROR;
    const char *v_mediaDescriptionSdp = Tcl_GetString(objv[2]);
    int rc = rtcAddTrack(raw_pc, v_mediaDescriptionSdp);
    return RtcReturnInt(interp, rc);
}

static int Cmd_tr_delete(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "tr"); return TCL_ERROR; }
    int raw_tr;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_tr) != TCL_OK) return TCL_ERROR;
    int rc = rtcDeleteTrack(raw_tr);
    RtcUnregisterAllCallbacks(raw_tr);
    return RtcReturnInt(interp, rc);
}

static int Cmd_tr_get_description(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "tr"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetTrackDescription, id);
}

static int Cmd_tr_get_mid(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "tr"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetTrackMid, id);
}

static int Cmd_tr_request_keyframe(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "tr"); return TCL_ERROR; }
    int raw_tr;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_tr) != TCL_OK) return TCL_ERROR;
    int rc = rtcRequestKeyframe(raw_tr);
    return RtcReturnInt(interp, rc);
}

static int Cmd_tr_request_bitrate(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "tr bitrate"); return TCL_ERROR; }
    int raw_tr;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_tr) != TCL_OK) return TCL_ERROR;
    int raw_bitrate;
    if (Tcl_GetIntFromObj(interp, objv[2], &raw_bitrate) != TCL_OK) return TCL_ERROR;
    int rc = rtcRequestBitrate(raw_tr, (unsigned int)raw_bitrate);
    return RtcReturnInt(interp, rc);
}

static int Cmd_tr_chain_rtcp_receiving_session(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "tr"); return TCL_ERROR; }
    int raw_tr;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_tr) != TCL_OK) return TCL_ERROR;
    int rc = rtcChainRtcpReceivingSession(raw_tr);
    return RtcReturnInt(interp, rc);
}

static int Cmd_tr_chain_rtcp_sr_reporter(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "tr"); return TCL_ERROR; }
    int raw_tr;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_tr) != TCL_OK) return TCL_ERROR;
    int rc = rtcChainRtcpSrReporter(raw_tr);
    return RtcReturnInt(interp, rc);
}

static int Cmd_tr_chain_rtcp_nack_responder(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "tr maxStoredPacketsCount"); return TCL_ERROR; }
    int raw_tr;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_tr) != TCL_OK) return TCL_ERROR;
    int raw_maxStoredPacketsCount;
    if (Tcl_GetIntFromObj(interp, objv[2], &raw_maxStoredPacketsCount) != TCL_OK) return TCL_ERROR;
    int rc = rtcChainRtcpNackResponder(raw_tr, (unsigned int)raw_maxStoredPacketsCount);
    return RtcReturnInt(interp, rc);
}

static void Tramp_tr_pli(int tr, void* ptr) {
    (void)ptr;
    RtcEnqueueNoArgs(tr, RTC_SLOT_TR_PLI);
}

static int Cmd_tr_on_pli(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "tr cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_TR_PLI, objv[2],
        (RtcSetterFn)rtcChainPliHandler, (void(*)(void))Tramp_tr_pli);
}

static void Tramp_tr_remb(int tr, unsigned int bitrate, void* ptr) {
    (void)ptr;
    RtcEnqueueInt(tr, RTC_SLOT_TR_REMB, (int)bitrate);
}

static int Cmd_tr_on_remb(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "tr cmdPrefix"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcRegisterCallback(interp, id, RTC_SLOT_TR_REMB, objv[2],
        (RtcSetterFn)rtcChainRembHandler, (void(*)(void))Tramp_tr_remb);
}

static int Cmd_id_set_track_rtp_timestamp(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 3) { Tcl_WrongNumArgs(interp, 1, objv, "id timestamp"); return TCL_ERROR; }
    int raw_id;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_id) != TCL_OK) return TCL_ERROR;
    int raw_timestamp;
    if (Tcl_GetIntFromObj(interp, objv[2], &raw_timestamp) != TCL_OK) return TCL_ERROR;
    int rc = rtcSetTrackRtpTimestamp(raw_id, (uint32_t)raw_timestamp);
    return RtcReturnInt(interp, rc);
}

static int Cmd__create_web_socket(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "url"); return TCL_ERROR; }
    const char *v_url = Tcl_GetString(objv[1]);
    int rc = rtcCreateWebSocket(v_url);
    return RtcReturnInt(interp, rc);
}

static int Cmd_ws_delete(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "ws"); return TCL_ERROR; }
    int raw_ws;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_ws) != TCL_OK) return TCL_ERROR;
    int rc = rtcDeleteWebSocket(raw_ws);
    RtcUnregisterAllCallbacks(raw_ws);
    return RtcReturnInt(interp, rc);
}

static int Cmd_ws_get_remote_address(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "ws"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetWebSocketRemoteAddress, id);
}

static int Cmd_ws_get_path(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "ws"); return TCL_ERROR; }
    int id;
    if (Tcl_GetIntFromObj(interp, objv[1], &id) != TCL_OK) return TCL_ERROR;
    return RtcCmd_OutString(interp, rtcGetWebSocketPath, id);
}

static int Cmd_wsserver_delete(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "wsserver"); return TCL_ERROR; }
    int raw_wsserver;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_wsserver) != TCL_OK) return TCL_ERROR;
    int rc = rtcDeleteWebSocketServer(raw_wsserver);
    RtcUnregisterAllCallbacks(raw_wsserver);
    return RtcReturnInt(interp, rc);
}

static int Cmd_wsserver_get_port(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "wsserver"); return TCL_ERROR; }
    int raw_wsserver;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_wsserver) != TCL_OK) return TCL_ERROR;
    int rc = rtcGetWebSocketServerPort(raw_wsserver);
    return RtcReturnInt(interp, rc);
}

static int Cmd__set_thread_pool_size(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd;
    if (objc != 2) { Tcl_WrongNumArgs(interp, 1, objv, "count"); return TCL_ERROR; }
    int raw_count;
    if (Tcl_GetIntFromObj(interp, objv[1], &raw_count) != TCL_OK) return TCL_ERROR;
    int rc = rtcSetThreadPoolSize((unsigned int)raw_count);
    return RtcReturnInt(interp, rc);
}

static int Cmd__preload(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd; (void)objv;
    if (objc != 1) { Tcl_WrongNumArgs(interp, 1, objv, ""); return TCL_ERROR; }
    rtcPreload();
    return TCL_OK;
}

static int Cmd__cleanup(void *cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[]) {
    (void)cd; (void)objv;
    if (objc != 1) { Tcl_WrongNumArgs(interp, 1, objv, ""); return TCL_ERROR; }
    rtcCleanup();
    return TCL_OK;
}

const RtcCommand RtcGeneratedCommands[] = {
    { "::rtc::pc::close", Cmd_pc_close },
    { "::rtc::pc::delete", Cmd_pc_delete },
    { "::rtc::pc::on-local-description", Cmd_pc_on_local_description },
    { "::rtc::pc::on-local-candidate", Cmd_pc_on_local_candidate },
    { "::rtc::pc::on-state-change", Cmd_pc_on_state_change },
    { "::rtc::pc::on-ice-state-change", Cmd_pc_on_ice_state_change },
    { "::rtc::pc::on-gathering-state-change", Cmd_pc_on_gathering_state_change },
    { "::rtc::pc::on-signaling-state-change", Cmd_pc_on_signaling_state_change },
    { "::rtc::pc::set-local-description", Cmd_pc_set_local_description },
    { "::rtc::pc::set-remote-description", Cmd_pc_set_remote_description },
    { "::rtc::pc::add-remote-candidate", Cmd_pc_add_remote_candidate },
    { "::rtc::pc::get-local-description", Cmd_pc_get_local_description },
    { "::rtc::pc::get-remote-description", Cmd_pc_get_remote_description },
    { "::rtc::pc::get-local-description-type", Cmd_pc_get_local_description_type },
    { "::rtc::pc::get-remote-description-type", Cmd_pc_get_remote_description_type },
    { "::rtc::pc::create-offer", Cmd_pc_create_offer },
    { "::rtc::pc::create-answer", Cmd_pc_create_answer },
    { "::rtc::pc::get-local-address", Cmd_pc_get_local_address },
    { "::rtc::pc::get-remote-address", Cmd_pc_get_remote_address },
    { "::rtc::pc::is-negotiation-needed", Cmd_pc_is_negotiation_needed },
    { "::rtc::pc::get-max-data-channel-stream", Cmd_pc_get_max_data_channel_stream },
    { "::rtc::pc::get-remote-max-message-size", Cmd_pc_get_remote_max_message_size },
    { "::rtc::common::on-open", Cmd_id_on_open },
    { "::rtc::common::on-closed", Cmd_id_on_closed },
    { "::rtc::common::on-error", Cmd_id_on_error },
    { "::rtc::common::on-message", Cmd_id_on_message },
    { "::rtc::common::close", Cmd_id_close },
    { "::rtc::common::delete", Cmd_id_delete },
    { "::rtc::common::is-open", Cmd_id_is_open },
    { "::rtc::common::is-closed", Cmd_id_is_closed },
    { "::rtc::common::max-message-size", Cmd_id_max_message_size },
    { "::rtc::common::get-buffered-amount", Cmd_id_get_buffered_amount },
    { "::rtc::common::set-buffered-amount-low-threshold", Cmd_id_set_buffered_amount_low_threshold },
    { "::rtc::common::on-buffered-amount-low", Cmd_id_on_buffered_amount_low },
    { "::rtc::common::get-available-amount", Cmd_id_get_available_amount },
    { "::rtc::common::on-available", Cmd_id_on_available },
    { "::rtc::pc::on-data-channel", Cmd_pc_on_data_channel },
    { "::rtc::pc::create-data-channel", Cmd_pc_create_data_channel },
    { "::rtc::dc::delete", Cmd_dc_delete },
    { "::rtc::dc::get-stream", Cmd_dc_get_stream },
    { "::rtc::dc::get-label", Cmd_dc_get_label },
    { "::rtc::dc::get-protocol", Cmd_dc_get_protocol },
    { "::rtc::pc::on-track", Cmd_pc_on_track },
    { "::rtc::pc::add-track", Cmd_pc_add_track },
    { "::rtc::track::delete", Cmd_tr_delete },
    { "::rtc::track::get-description", Cmd_tr_get_description },
    { "::rtc::track::get-mid", Cmd_tr_get_mid },
    { "::rtc::track::request-keyframe", Cmd_tr_request_keyframe },
    { "::rtc::track::request-bitrate", Cmd_tr_request_bitrate },
    { "::rtc::track::chain-rtcp-receiving-session", Cmd_tr_chain_rtcp_receiving_session },
    { "::rtc::track::chain-rtcp-sr-reporter", Cmd_tr_chain_rtcp_sr_reporter },
    { "::rtc::track::chain-rtcp-nack-responder", Cmd_tr_chain_rtcp_nack_responder },
    { "::rtc::track::on-pli", Cmd_tr_on_pli },
    { "::rtc::track::on-remb", Cmd_tr_on_remb },
    { "::rtc::common::set-track-rtp-timestamp", Cmd_id_set_track_rtp_timestamp },
    { "::rtc::create-web-socket", Cmd__create_web_socket },
    { "::rtc::ws::delete", Cmd_ws_delete },
    { "::rtc::ws::get-remote-address", Cmd_ws_get_remote_address },
    { "::rtc::ws::get-path", Cmd_ws_get_path },
    { "::rtc::wsserver::delete", Cmd_wsserver_delete },
    { "::rtc::wsserver::get-port", Cmd_wsserver_get_port },
    { "::rtc::set-thread-pool-size", Cmd__set_thread_pool_size },
    { "::rtc::preload", Cmd__preload },
    { "::rtc::cleanup", Cmd__cleanup },
    { NULL, NULL }
};
